from typing import Any

def is_builtin_class_instance(obj: Any) -> bool: ...

class TlbError(Exception): ...

class TlbScheme:
    def serialize(self, *args: Any, **kwargs: Any) -> Any: ...
    @classmethod
    def deserialize(cls, *args: Any, **kwargs: Any) -> Any: ...
